[build-system]
requires=["setuptools>=68"]
build-backend="setuptools.build_meta"

[project]
name="mem20webassemblycomponentlabz"
version="1.0.0"
description='Run language-neutral components with explicit interfaces and strong isolation'
requires-python=">=3.11"

[project.scripts]
mem20webassemblycomponentlabz="mem20webassemblycomponentlabz.core:cli"

[tool.setuptools]
packages=["mem20webassemblycomponentlabz"]
[tool.setuptools.package-data]
mem20webassemblycomponentlabz=["roadmap.json"]
