"""Pinned-block delivery.

A new agent's onboarding survives session boundaries by being pinned in mem20 —
the same mechanism that carries `pickle-voice` and `spacebunny-life`. Pinned
blocks are immune to pruning and loadable at session start.

This module cannot itself call the mem20 memory tools: they are exposed to the
*agent* running the onboarding, not to a standalone Python process. Rather than
pretend, it emits the exact requests needed and says plainly that a human or
agent with mem20 tool access must apply them. That boundary is real and it is
documented rather than faked.
"""

from __future__ import annotations

import json
from pathlib import Path

from .pack import AgentProfile, Pack


def build_requests(profile: AgentProfile, pack_dir: Path) -> list[dict]:
    """The exact mem20 tool calls that register this agent's durable context."""
    guide = (pack_dir / "HIRE-GUIDE.md").read_text(encoding="utf-8")
    governance = (pack_dir / "GOVERNANCE.md").read_text(encoding="utf-8")

    return [
        {
            "tool": "mem20_memory_pin_block",
            "arguments": {
                "block_id": profile.block_id,
                "content": guide,
                "reason": (
                    f"Hire guide for {profile.name}, generated by mem20AIonbordz from "
                    f"verified host facts. Pinned so it survives pruning and is loadable "
                    f"at session start."
                ),
            },
        },
        {
            "tool": "mem20_memory_pin_block",
            "arguments": {
                "block_id": f"{profile.slug}-governance",
                "content": governance,
                "reason": (
                    f"Governance rules binding on {profile.name}, each with the reason it "
                    f"exists. Pinned as a core reference."
                ),
            },
        },
    ]


def write_requests(pack_dir: Path, requests: list[dict]) -> Path:
    """Persist the requests next to the pack for whoever applies them."""
    path = pack_dir / "PIN-REQUESTS.json"
    payload = {
        "_note": (
            "Apply each entry by calling the named mem20 tool with the given arguments. "
            "A standalone script cannot call these tools directly - an agent with mem20 "
            "tool access applies them. See FIND-ME.txt."
        ),
        "requests": requests,
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def apply(pack_dir: Path) -> tuple[Path, list[dict]]:
    """Build and write the pin requests for a generated pack."""
    manifest = json.loads((pack_dir / "onboarding.json").read_text(encoding="utf-8"))
    agent = manifest["agent"]
    profile = AgentProfile(
        name=agent["name"],
        role=agent.get("role", "mem20 agent"),
        mission=agent.get("mission", ""),
        capabilities=list(agent.get("capabilities") or []),
        values=list(agent.get("values") or []),
        voice=agent.get("voice", ""),
        reporting_to=agent.get("reporting_to", "Jayson"),
    )
    requests = build_requests(profile, pack_dir)
    path = write_requests(pack_dir, requests)
    return path, requests


def render(pack_dir: Path, path: Path, requests: list[dict]) -> str:
    lines = [
        f"Wrote {path}",
        "",
        f"{len(requests)} pinned block(s) prepared for:",
    ]
    for req in requests:
        lines.append(f"  - {req['arguments']['block_id']}")
    lines += [
        "",
        "These are written as requests, not applied. A standalone process cannot call",
        "the mem20 memory tools - they belong to the agent running the onboarding.",
        f"Ask that agent to read {path} and issue each call with the arguments given.",
    ]
    return "\n".join(lines)