"""Renders the index as an agent-readable appendix."""

from __future__ import annotations

from typing import Any

CATEGORY_LABEL = {
    "organ": "Native subsystem (mem20*z)",
    "service": "Engine / service (un-prefixed by design)",
    "other": "Other top-level",
}


def render_markdown(index: dict[str, Any]) -> str:
    totals = index.get("totals", {})
    lines: list[str] = []
    lines.append("# mem20 Codebase Sitemap")
    lines.append("")
    lines.append(
        f"_Generated by `sitemap build` at {index.get('generated_at')} "
        f"from {index.get('root')} in {index.get('scan_seconds')}s. "
        "Do not hand-edit; rebuild instead._"
    )
    lines.append("")
    lines.append("## What this is")
    lines.append("")
    lines.append(
        "A machine-readable map of this monorepo so an agent can find the right subsystem "
        "without being told. Companion data lives in `.sitemap/sitemap.json`; query it with "
        "`/sitemap search \"<terms>\"` and drill in with `/sitemap show <subsystem>`."
    )
    lines.append("")
    lines.append("## Totals")
    lines.append("")
    lines.append(f"- Subsystems indexed: **{totals.get('subsystems', 0)}**")
    lines.append(f"- Source files: **{totals.get('files', 0)}**")
    lines.append(f"- Code lines (excludes data/docs): **{totals.get('code_lines', 0):,}**")
    lines.append(f"- All non-blank source lines (incl. json/md): **{totals.get('lines', 0):,}**")
    langs = totals.get("languages", {})
    if langs:
        top = ", ".join(f"{k} ({v})" for k, v in list(langs.items())[:8])
        lines.append(f"- Languages: {top}")
    categories = totals.get("categories", {})
    if categories:
        parts = ", ".join(f"{k} ({v})" for k, v in categories.items())
        lines.append(f"- Categories: {parts}")
    lines.append("")

    subsystems = index.get("subsystems", [])
    for category in ("organ", "service", "other"):
        group = [s for s in subsystems if s.get("category") == category]
        if not group:
            continue
        lines.append(f"## {CATEGORY_LABEL.get(category, category)}")
        lines.append("")
        lines.append("| Subsystem | Code lines | Tests | Entry points | What it is |")
        lines.append("|---|---:|---:|---|---|")
        for entry in sorted(group, key=lambda e: (-e.get("code_lines", 0), e["name"])):
            summary = entry.get("description") or entry.get("readme_summary") or ""
            summary = summary.replace("|", "/").replace("\n", " ")
            if len(summary) > 150:
                summary = summary[:147] + "..."
            scripts = ", ".join(f"`{k}`" for k in sorted(entry.get("entry_points", {}))) or "-"
            lines.append(
                f"| `{entry['name']}` | {entry.get('code_lines', 0)} | "
                f"{entry.get('test_files', 0)} | {scripts} | {summary} |"
            )
        lines.append("")

    lines.append("## Entry points by subsystem")
    lines.append("")
    lines.append("```")
    for entry in subsystems:
        for script, target in sorted(entry.get("entry_points", {}).items()):
            lines.append(f"{script} = {target}")
    lines.append("```")
    lines.append("")

    lines.append("## Reading order for a new agent")
    lines.append("")
    lines.append("1. Run `/sitemap search \"<what you need>\"` before grepping the tree.")
    lines.append("2. Read the subsystem `README.md` before its code; summaries above are one-line only.")
    lines.append("3. Check `AGENTS.md` in `/root` for standing rules that override local convention.")
    lines.append("4. Check `toolchest show <name>` before building anything new; most needs are already met.")
    lines.append("")
    return "\n".join(lines)


def render_terminal(index: dict[str, Any]) -> str:
    totals = index.get("totals", {})
    lines = [
        f"root        {index.get('root')}",
        f"generated   {index.get('generated_at')} ({index.get('scan_seconds')}s)",
        f"subsystems  {totals.get('subsystems', 0)}",
        f"files       {totals.get('files', 0)}",
        f"code lines  {totals.get('code_lines', 0)}",
        f"all lines   {totals.get('lines', 0)}",
    ]
    langs = totals.get("languages", {})
    if langs:
        lines.append("languages   " + ", ".join(f"{k}:{v}" for k, v in list(langs.items())[:8]))
    for category, count in (totals.get("categories") or {}).items():
        lines.append(f"{category:11} {count}")
    return "\n".join(lines)
